### ISSUE TITLE
pruneNullOrEmpty

### ISSUE THREAD

**Issue by hoseinprd** [fullstacksjs/toolbox#15]
### Function signature

```typescript
pruneNullOrEmpty(obj: T): T;
```

### What utility function do you need?

removing null or empty values from an object.

### What motivates us?

it's common to have an object which contains values with an empty string or null, in most cases to have a valid and clear object we need to ensure the null or empty string is removed from an object.

### List of examples

```typescript
pruneNullOrEmpty({ firstName: null, lastName: "PRD"  }) // { lastName: "PRD" }
pruneNullOrEmpty({ firstName: '', lastName: "PRD"  })  // { lastName: "PRD" }
pruneNullOrEmpty({ firstName: '', lastName: "PRD", age: null  }) // { lastName: "PRD"}
```

**Comment by frontendmonster** [comment]
It's nice to have.
Also very useful when dealing with forms and APIs.

**Comment by frontendmonster** [comment]
Thanks a lot :pray:
