### ISSUE TITLE
tryCatch + nullableTryCatch

### ISSUE THREAD

**Issue by AmirabbasJ** [fullstacksjs/toolbox#31]
### Function signature

```typescript
type TryCatch = <T, E>(f: () => T, onErr: (e?: unknown) => E) => E | T
type AsyncTryCatch = <T, E>(f: () => Promise<T>, onErr: (e?: unknown) => E) => Promise<E | T>
type NTryCatch = <T>(f: () => T) => Nullable<T>
type AsyncNTryCatch = <T>(f: () => Promise<T>) => Nullable<T>
```

### What utility function do you need?

the functions purpose is to abstract the nasty try-catch syntax into a function

### List of examples

```typescript
 const f = () => {
  if (Math.random() > 0.5) return true;
  throw Error('something bad happened');
};

const trueOrErr = TryCatch(f,  () => 'bad luck')  // true | 'bad luck'
const dataOrErr = await AsyncTryCatch( () => fetch('hello'),  () => 'failed to fetch')  // data | 'failed to fetch'
const trueOrNull = await N.asyncTryCatch(f)  // true | null
const dataOrNull = await N.asyncTryCatch(() => fetch('hello'))  // data | null
```

### Note:

in the last two line the `N` refers to the object which holds the nullable module
so we also need to have such syntax for nullables:
```typescript
import * as N from 'toolbox/nullable';

N.Nullable // refers to the typescript nullable type not a value
N.asyncTryCatch, N.tryCatch // refers to the nullable functions which was mentioned above

```

**Comment by ASafaeirad** [comment]
It seems nice :+1: 
But why should it work with promises?

**Comment by AmirabbasJ** [comment]
@ASafaeirad 
You're right 
it could be much more general than being only for promises
I'll fix the signature

**Comment by AmirabbasJ** [comment]
@ASafaeirad
You're right
it could be much more general than being just for promises
but in that case we should have one for general use and one specifically for promises
because the return type won't really work out this way

if we change it to 
```typescript
type TryCatch = <T, E>(f: () => T, onErr: () => E) => E | T
```

this way if the T is of type e.g ```typescript Promise<string>``` and the E is `number` then the return type would be ```typescript Promise<string> | number```
which is not what we want

so in conclusion we need a new function for each wrapper type
I'll fix the signature

**Comment by AmirabbasJ** [comment]
I think we also need a namespace for each type we have so that we can have such thing

```typescript
import * as NP from 'toolbox/NullablePromise'
import { tryCatch } from 'toolbox/functions'

tryCatch() 
NP.tryCatch()
```

**Comment by ASafaeirad** [comment]
It makes sense. I agree.

**Comment by Keivan-sf** [comment]
Will look into this one, feel free to assign

**Comment by Keivan-sf** [comment]
Do we really need this syntax?
```ts
N.asyncTryCatch()
N.tryCatch()
```
Cause right now nullable functions are exposed like this:
```ts
import { concatArrays } from '@fullstacksjs/toolbox'
```

If we want to have a syntax like `N.tryCatch()` and also prevent confusion with the normal `tryCatch` , we need to export a single nullable object rather than its utilities, which is breaking.
Or maybe I'm just missing something

**Comment by ASafaeirad** [comment]
This is an old issue, we gave up with namespaces.
