### ISSUE TITLE
[Proposal]: throttle

### ISSUE THREAD

**Issue by ASafaeirad** [fullstacksjs/toolbox#45]
### Scope
`function`

### Function Signature

```typescript
function throttle<T extends Function>(options: { interval: number; isImmediate?: boolean }, f: T): T
```

### Motivation

In numerous applications, there are functions that are executed frequently, such as during window resizing, text input, or mouse movements. These repeated function calls might cause performance bottlenecks, particularly when they lead to hefty computations or disruptive visual updates.

The `throttle` function serves to control the execution rate of a function.

**Comment by hamed-bavar** [comment]
may I work on this issue?

**Comment by ASafaeirad** [comment]
Of course, feel free to open a PR
