### ISSUE TITLE
[Proposal]: uniq

### ISSUE THREAD

**Issue by mahdi-sheibak** [fullstacksjs/toolbox#48]
### Scope
`array`

### Function Signature

```typescript
function uniq<T extends any[]>(array: T): T
```

### Motivation

The motivation behind the `uniq` function is to simplify the process of obtaining a new array with all duplicate values removed. It aims to provide an efficient and convenient way to remove duplicates from an array, without modifying the original array.

**Comment by hamed-bavar** [comment]
How should elements be compared with each other? through deep comparison or just by reference?

**Comment by mahdi-sheibak** [comment]
see this example: https://codesandbox.io/p/sandbox/uniq-example-czqq98
@hamed-bavar @ASafaeirad

**Comment by hamed-bavar** [comment]
I think `JSON.stringify` is not the best choice for deeply comparing two objects, It is not going to work as expected for function and symbol types and some others, so it will have different behavior for different types of objects. I think using `===` is a better because it will always return false for objects that do not have the same reference.

**Comment by mahdi-sheibak** [comment]
please share a sandbox

**Comment by mahdi-sheibak** [comment]
This is good, but does not work on an array of objects. How we can provide this on your implementation?

```typescript
anotherImplementation([
    {name:"John"},
    {name:"John"},
])
```

**Comment by hamed-bavar** [comment]
I know, as I said this implementation is just a shallow comparison (===) for the sake of keeping everything simple and performant. For deep comparison you need more than that, just a JSON.stringify. the uniq function should be prepared for comparing functions, dates, Symbols, complex nested objects, etc which makes the function very messy and slow.

**Comment by hamed-bavar** [comment]
@ASafaeirad, @mahdi-sheibak. what if we shallow compare by default unless a comparison function was provided. but the time complexity would be more than previous implementation since the compare function of sets in JavaScript can not be changed and we need to use array instead.

**Comment by mahdi-sheibak** [comment]
> I know, as I said this implementation is just a shallow comparison (===) for the sake of keeping everything simple and performant [just like uniq function in lodash]. For deep comparison you need more than that, just a JSON.stringify. the uniq function should be prepared for comparing functions, dates, Symbols, complex nested objects, etc which makes the function very messy and slow.

I completely agree with you! How about we take inspiration from lodashjs and create three useful functions: 'uniq' to filter out duplicate values, 'uniqBy' to filter duplicates by a specific key, and 'uniqWith' to filter duplicates based on custom comparison logic?

**Comment by ASafaeirad** [comment]
Agree, object types are not the same in the language therefore `uniq` function should not mark them as duplicates. let's keep it simple and compare with `Object.is`
