### ISSUE TITLE
[Proposal]: merge

### ISSUE THREAD

**Issue by ASafaeirad** [fullstacksjs/toolbox#53]
### Function Signature

```ts
function merge(obj1: T, obj2: U, composer?: (value1, value2, key, obj1, obj2): DeepMerge<T, U>
```

### Motivation

It is quite useful for configuration management.

**Comment by abxlfazl** [comment]
I am working on this, the function signature confused me a bit
The composer is callback function and DeepMerge type is for merge function ?

**Comment by ASafaeirad** [comment]
Hey, the composer function is used when it encounters the same path in both objects, let's say we have.

```ts
const obj1 = { item1: { count: 1 } };
const obj2 = { item1: { count: 2 } };
const result = merge(obj1, obj2) // { item1: { count: 2 } }
```

Let's assume we want to merge these to object to `{ item1: { count: 3 } }`, so it means when there's a common path in both objects we should be able to decide how the merge should happen.

The composer function helps here to define the merge mechanism, as the merge function iterates over objects when it finds a common path in objects, it calls the composer function and uses the return value as the result.

So in our case, if we want to sum the count, we can call the function like:

```ts
const sum = merge(
  obj1,
  obj2,
  (value1, value2, key) => {
    if(key === 'count') return value1 + value2
    return merge.defaultComposer(value1, value2);
  }
)
```

The `defaultComposer` is the standard composer function the merge uses by default it should:
- If the values are objects it should merge the object.
- If the values are array it should concatenate them.
- Otherwise, it should use the `value2`.

**Comment by abxlfazl** [comment]
Hi, thank you for your explanations, I got it.
