### ISSUE TITLE
[Bug]: External `tryOr` link in the docs

### ISSUE THREAD

**Issue by ShayanTheNerd** [fullstacksjs/toolbox#54]
### Describe the issue

In the docs, there's an external link among the __Function__ drop down menu links, navigating to the `tryOr` utility section.

The main link: https://toolbox.fullstacksjs.com/function/tryOr

The external link: https://toolbox.fullstacksjs.com/function/tryOr#

[Click to preview](https://toolbox.fullstacksjs.com/function/tryOr#:~:text=throttle-,tryor,-Tryor)

### Expected Behavior

There should be only one link on the __Function__ drop down menu navigating to the `tryOr` utility page. 

### Actual Behavior

There are two links (the main one and an external one) on the __Function__ drop down menu navigating to the `tryOr` utility page.

**Comment by ASafaeirad** [comment]
Hey, thanks for reporting
Fixed on #56.
