### ISSUE TITLE
[Proposal]: bindArgs (only-args, exclude `thisArg`)

### ISSUE THREAD

**Issue by mikoloism** [fullstacksjs/toolbox#58]
### Function Signature

```typescript
declare global {
  export interface Function {
    bindArgs<T, A extends unknown[]>(this: T, ...args: A): OmitThisParameter<T>;
  }
}
```

### Motivation

With the `bind` method, we must pass `thisArg` as the first argument to the function we want to bind (the target). What if we didn't want to go through it? Yes, there is a solution below

```typescript
const bound = fn.bind(null, ...otherArgsToBind);
// Or
const bound = fn.bind({}, ...otherArgsToBind);
```

But, what if we don't want to modify `thisArg`? What should be passed?

```typescript
const bound = fn.bindArgs(...onlyArgsToBind);
// Then
Bound(...anotherArgsNotInBind);
```

In the actual example, it was used in `chalk`, perhaps, when we write:

```typescript
class LogColor {
  public static readonly DEBUG = chalk.gray.bind(null, ' [DEBUG] ');
  public static readonly INFO = chalk.blue.bind(null, ' [INFO] ');
  public static readonly WARN = chalk.yellow.bind(null, ' [WARN] ');
  public static readonly ERROR = chalk.red.bind(null, ' [ERROR] ');
}
```

Or in miniaml

```typescript
const logColor = {
  DEBUG: chalk.gray.bind(null, ' [DEBUG] '),
  INFO: chalk.blue.bind(null, ' [INFO] '),
  WARN: chalk.yellow.bind(null, ' [WARN] '),
  ERROR: chalk.red.bind(null, ' [ERROR] '),
};
```

We need to pass `null` exactly to pass `thisArg`

**Comment by ASafaeirad** [comment]
Hi @mikoloism, thanks for your contribution.

We must ensure that the functions we introduce are free from side effects, which is the main motivation behind this library.

Also, manipulating the standard Javascript API through an external library is considered bad practice.

So we can define this function like `bound = bindArgs(fn, ...args)`

**Comment by mikoloism** [comment]
Thank @ASafaeirad for your attention

Sure, changes will be applied soon
