### ISSUE TITLE
[Proposal]: Camel case maker in order to format Json/data object keys that we get from backend

### ISSUE THREAD

**Issue by gooddevil79** [fullstacksjs/toolbox#67]
### Function Signature

```typescript
const toCamel = value => {
	return value.replace(/([-_][a-z])/gi, $1 => {
		return $1.toUpperCase().replace("-", "").replace("_", "");
	});
};

const keysToCamel = (obj) => {
	if (isObject(obj)) {
		const n = {};

		Object.keys(obj).forEach((k) => {
			n[toCamel(k)] = keysToCamel(obj[k]);
		});

		return n;
	} else if (isArray(obj)) {
		return obj.map((i) => {
			return keysToCamel(i);
		});
	}

	return obj;
};
```

### Motivation

As we know ,backend developers usually naming keys in '**snake_case**"format, and in JavaScript we use **CamelCase**, with this helper function we can pass a string like **hello_world** and get **"helloWorld"** in return, also it we can use **"keysToCamel"** in order to format entire object keys at a time

**Comment by ASafaeirad** [comment]
Thanks @gooddevil79, However, the motivation is not a reliable solution.
