### ISSUE TITLE
[Proposal]: Format price in a easy way

### ISSUE THREAD

**Issue by gooddevil79** [fullstacksjs/toolbox#69]
### Function Signature

```typescript
const priceFormat = (value) => {
	return `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
};
```

### Motivation

simply pass a **number** and get a **nu,mber** ¯\_(ツ)_/¯

**Comment by ASafaeirad** [comment]
Hello, @gooddevil79. Thanks for the contribution.

There's a standard `Intl.NumberFormat` API for this usecase.
